<a href="https://colab.research.google.com/github/gauravd12345/language_models/blob/main/seq2seq/seq2seq.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import re
import random
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split

import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"device: {device}")

dataset = "hf://datasets/PaulineSanchez/Translation_words_and_sentences_english_french/data/train-00000-of-00001-3d14582ea46e1b17.parquet"
df = pd.read_parquet(dataset)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


device: cuda


In [51]:
c1, c2 = df.columns
enc = np.array(df[c1])
dec = np.array(df[c2])

for i in np.random.choice(np.arange(len(df)), 10):
  print(f"{enc[i]:<50} | {dec[i]}")

Are you a registered voter?                        | Êtes-vous un électeur inscrit ?
I was surprised by what I learned.                 | Je fus surpris par ce que j'appris.
I started this topic.                              | J'ai ouvert ce sujet.
I wish I could write as well as Tom.               | J'aimerais pouvoir écrire aussi bien que Tom.
He had a queer expression on his face.             | Il faisait une drôle de tête.
I lost my wallet somewhere around here.            | J'ai perdu mon portefeuille quelque part par ici.
The TV doesn't work.                               | La télévision ne fonctionne pas.
The whole world is watching.                       | Le monde entier nous regarde.
I started a fire right away.                       | J'ai tout de suite démarré un feu.
Don't talk to me.                                  | Ne me parle pas !


In [74]:
""" setup for encoder dataset """
enc_words = [word_tokenize(seq) for seq in enc]
enc_vocab = set()
for seq in enc_words:
  for word in seq:
    enc_vocab.add(word)

enc_vocab.add("<EOS>")
enc_vocab = sorted(enc_vocab)
enc_vocab_len = len(enc_vocab)

etoi, itoe = {}, {}
for i in range(enc_vocab_len):
    etoi[enc_vocab[i]] = i
    itoe[i] = enc_vocab[i]

print(f"english vocab size: {enc_vocab_len}")
print(enc_vocab[:10])

""" setup for decoder dataset """
dec_words = [word_tokenize(seq) for seq in dec]
dec_vocab = set()
for seq in dec_words:
  for word in seq:
    dec_vocab.add(word)

dec_vocab.add("<EOS>")
dec_vocab = sorted(dec_vocab)
dec_vocab_len = len(dec_vocab)

dtoi, itod = {}, {}
for i in range(dec_vocab_len):
    dtoi[dec_vocab[i]] = i
    itod[i] = dec_vocab[i]

print(f"\nfrench vocab size: {enc_vocab_len}")
print(dec_vocab[:10])

english vocab size: 16895
['!', '$', '%', '&', "'", "''", "'anticonstitutionnellement", "'bribery", "'d", "'em"]

french vocab size: 16895
['!', '$', '%', '&', "'", "''", "'Spot", "'achète", "'maison", "'oublie"]


In [ ]:
""" Hyperparameters """

seq_len = 10  # sequence length of the encoder output/decoder input vector


In [80]:
E = []
for sentence in enc:
  seq = []
  tok = word_tokenize(sentence) + ["<EOS>"]
  for word in tok:
    e_i = etoi[word]
    seq.append(e_i)
  E.append(torch.tensor(seq))

D = []
for sentence in dec:
  seq = []
  tok = word_tokenize(sentence) + ["<EOS>"]
  for word in tok:
    d_i = dtoi[word]
    seq.append(d_i)
  D.append(torch.tensor(seq))

for i in range(10): # tokenized english to french translations
  print(E[i], D[i])

tensor([1440,   19,  285]) tensor([3832,    0,  232])
tensor([2414,    0,  285]) tensor([942,   0, 232])
tensor([2414,    0,  285]) tensor([939,   0, 232])
tensor([3046,  286,  285]) tensor([3436,  233,  232])
tensor([3096,    0,  285]) tensor([30686,  5230,     0,   232])
tensor([1187,    0,  285]) tensor([  528, 14028,     0,   232])
tensor([1428,    0,  285]) tensor([30684, 17160,     0,   232])
tensor([1611,   19,  285]) tensor([3843,   15,  232])
tensor([2667,    0,  285]) tensor([30686, 27911,     0,   232])
tensor([2667,    0,  285]) tensor([4012,    0,  232])


In [ ]:
class EncoderRNN(nn.Module):
    def __init__(self):
        super().__init__()


    def forward(self, w, h):
        return

encoder = EncoderRNN().to(device)

In [ ]:
class EncoderRNN(nn.Module):
    def __init__(self):
        super().__init__()


    def forward(self, w, h):
        return

encoder = EncoderRNN().to(device)