In [ ]:
import numpy as np
from nltk.corpus import brown

vocab = np.unique(brown.words())

""" Hyperparameters """
vocab_size = len(vocab)
activations = 100

# print("Vocabulary Size: ", vocab_size)
# print("Vocabulary: ", vocab)

Vocabulary:  ['!' '$.027' '$.03' ... 'zu' 'zur' '{0,T}']


In [ ]:
""" one hot encoding for the vocabulary """
word_encoding = np.zeros((vocab_size, vocab_size))
word_encoding[np.arange(vocab_size), np.arange(vocab_size)] = 1

print(word_encoding)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [44]:
import torch
import torch.nn as nn

class Skipgram(nn.Module):
    def __init__(self):
        super().__init__() # neural network inherits from nn.Module

        """ skipgram network layers """
        self.l1 = nn.Linear(vocab_size, activations)
        self.relu = nn.ReLU()
        self.l2 = nn.Linear(vocab_size, activations) # nn.CrossEntropyLoss will apply softmax

    """ forward pass of data """
    def forward(self, x):
        x = self.l1(x)
        x = self.relu(x)
        logits = self.l2(x)
        return logits
    
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Using {device} device")


Using mps device


In [45]:
model = Skipgram()